<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <ImplicitUsings>enable</ImplicitUsings>
    <Nullable>enable</Nullable>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
    <AssemblyName>Shirobot.Plugin.RssSubscriber</AssemblyName>
    <RootNamespace>Shirobot.Plugin.RssSubscriber</RootNamespace>
    <ShiroBotPluginPackagingEnabled>true</ShiroBotPluginPackagingEnabled>
    <ShiroBotPluginSharedAssemblies>ShiroBot.Model.QQ;ShiroBot.Model.Discord;ShiroBot.Model.Telegram</ShiroBotPluginSharedAssemblies>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="ShiroBot.SDK" Version="0.9.8" />
    <Content Include="Assets\config.toml" CopyToOutputDirectory="PreserveNewest" TargetPath="config.toml" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Shirobot.Plugin.RssSubscriber.Tests" />
  </ItemGroup>
</Project>
